server:
  port: ${SERVER.PORT:8008}
  timeout: ${SERVER.TIMEOUT:10}

api:
  Login:
    method: POST
    url: login
  Logout:
    method: GET
    url: logout

  UserCreate:
    method: POST
    url: user
  UserRead:
    method: GET
    url: user/{id}
  UsersRead:
    method: GET
    url: user
  UserUpdate:
    method: PUT
    url: user/{id}
  UserEdit:
    method: GET
    url: user/{id}/edit
  UserDelete:
    method: DELETE
    url: user/{id}

  SizeCreate:
    method: POST
    url: size
  SizeRead:
    method: GET
    url: size/{id}
  SizesRead:
    method: GET
    url: size
  SizeUpdate:
    method: PUT
    url: size/{id}
  SizeEdit:
    method: GET
    url: size/{id}/edit
  SizeDelete:
    method: DELETE
    url: size/{id}


accessExceptions:
  list:
    - Login
    - Logout
