server:
  port: ${SERVER.PORT:8008}
  timeout: ${SERVER.TIMEOUT:10}

api:
  UserCreate:
    method: POST
    url: user
  UserRead:
    method: GET
    url: user/{id}
  UsersRead:
    method: GET
    url: user
  UserUpdate:
    method: PUT
    url: user/{id}
  UserEdit:
    method: GET
    url: user/{id}/edit
  UserDelete:
    method: DELETE
    url: user/{id}
  Login:
    method: POST
    url: login
  Logout:
    method: GET
    url: logout

accessExceptions:
  list:
    - Login
    - Logout
