server:
  port: ${SERVER.PORT:8008}
  timeout: ${SERVER.TIMEOUT:10}

api:
  Login:
    method: POST
    url: login
  Logout:
    method: GET
    url: logout

  UserCreate:
    method: POST
    url: user
  UserRead:
    method: GET
    url: user/{id}
  UsersRead:
    method: GET
    url: user
  UserUpdate:
    method: PUT
    url: user/{id}
  UserEdit:
    method: GET
    url: user/{id}/edit
  UserDelete:
    method: DELETE
    url: user/{id}

  CategoryCreate:
    method: POST
    url: category
  CategoryRead:
    method: GET
    url: category/{id}
  CategoriesRead:
    method: GET
    url: category
  CategoryUpdate:
    method: PUT
    url: category/{id}
  CategoryEdit:
    method: GET
    url: category/{id}/edit
  CategoryDelete:
    method: DELETE
    url: category/{id}
  CategoryOptions:
    method: GET
    url: category/options

  BrandCreate:
    method: POST
    url: brand
  BrandRead:
    method: GET
    url: brand/{id}
  BrandsRead:
    method: GET
    url: brand
  BrandUpdate:
    method: PUT
    url: brand/{id}
  BrandEdit:
    method: GET
    url: brand/{id}/edit
  BrandDelete:
    method: DELETE
    url: brand/{id}
  BrandOptions:
    method: GET
    url: brand/options

  GenderCreate:
    method: POST
    url: gender
  GenderRead:
    method: GET
    url: gender/{id}
  GendersRead:
    method: GET
    url: gender
  GenderUpdate:
    method: PUT
    url: gender/{id}
  GenderEdit:
    method: GET
    url: gender/{id}/edit
  GenderDelete:
    method: DELETE
    url: gender/{id}
  GenderOptions:
    method: GET
    url: gender/options

  ColorCreate:
    method: POST
    url: color
  ColorRead:
    method: GET
    url: color/{id}
  ColorsRead:
    method: GET
    url: color
  ColorUpdate:
    method: PUT
    url: color/{id}
  ColorEdit:
    method: GET
    url: color/{id}/edit
  ColorDelete:
    method: DELETE
    url: color/{id}
  ColorOptions:
    method: GET
    url: color/options

  ProductCreate:
    method: POST
    url: product
  ProductRead:
    method: GET
    url: product/{id}
  ProductsRead:
    method: GET
    url: product
  ProductUpdate:
    method: PUT
    url: product/{id}
  ProductEdit:
    method: GET
    url: product/{id}/edit
  ProductDelete:
    method: DELETE
    url: product/{id}
  ProductCards:
    method: GET
    url: product-cards


accessExceptions:
  list:
    - Login
    - Logout
